### ISSUE TITLE
Fixtures loading error on a boolean using a behavior

### ISSUE THREAD

**Issue by ClementGautier** [propelorm/PropelBundle#205]
Hi,

I created a behavior which adds a field "is_active" on an entity. When I load my fixtures, the field "is_active" remains at 1. When I use a boolean field everything goes well.

I tried with:

``` yml
Foo\BarBundle\Model\Voucher:
    Voucher_1:
        code: EDUCTEST1
        used_by: User_2
        is_active: false
```

and

``` yml
Foo\BarBundle\Model\Voucher:
    Voucher_1:
        code: EDUCTEST1
        used_by: User_2
        is_active: 0
```

The behavior is quite simple, you can have a look on it if you want : https://github.com/ClementGautier/ActivatableBehavior

Do you have an idea on how to solve the problem?
