### ISSUE TITLE
fosuser model not generated

### ISSUE THREAD

**Issue by lionelbzv** [propelorm/PropelBundle#215]
Hello,

After updating my project to use sf2.2 (instead of 2.1), i cannot used my admin because of a bug in the fosuserbundle. After somes searches around, i've found that the "om" and "map" dir are are not created anymore during the "propel:build-model" process: the schema of fosuser it not read anymore!

my composer.json is now:

``` yaml
{
(...)
    "require": {
        "php": ">=5.3.3",

        "symfony/symfony": "2.2.*",

        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",

        "twig/extensions": "1.0.*",

        "symfony/assetic-bundle": "2.1.*",
        "symfony/swiftmailer-bundle": "2.2.*",
        "symfony/monolog-bundle": "2.2.*",
        "symfony/twig-bridge": "2.2.*",

        "sensio/distribution-bundle": "2.2.*",
        "sensio/framework-extra-bundle": "2.2.*",
        "sensio/generator-bundle": "2.2.*",

        "jms/security-extra-bundle": "1.4.*",
        "jms/di-extra-bundle": "1.3.*",

        "friendsofsymfony/user-bundle": "*",

        "propel/propel-bundle": "1.2.*",
        "craftyshadow/propel-equalnest-behavior": "dev-master",

(...)
    },
    "scripts": {
        "post-install-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "minimum-stability": "dev",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "symlink",
        "branch-alias": {
            "dev-master": "2.2-dev"
        }
    }
}
```

Thanks for help.
