### ISSUE TITLE
add UniqueFieldValidator

### ISSUE THREAD

**Issue by ienzam** [propelorm/PropelBundle#242]
`UniqueFieldValidtor` can check a field for uniqueness, so that we can do

```
Some\DemoBundle\Model\User:
    properties:
        username:
            - Propel\PropelBundle\Validator\Constraints\UniqueField:
                message: some.custom.message
```
