### ISSUE TITLE
Bug in PropelExtension::dbalLoad aliasing default connection

### ISSUE THREAD

**Issue by shane-l** [propelorm/PropelBundle#295]
I'm using multiple connections with the propel bundle as per the docs:

``` yaml
# app/config/config*.yml
propel:
    dbal:
        default_connection:         conn1
        connections:
            conn1:
                driver:             mysql
                user:               root
                password:           null
                dsn:                mysql:host=localhost;dbname=db1
            conn2:
                driver:             mysql
                user:               root
                password:           null
                dsn:                mysql:host=localhost;dbname=db2
```

I'm running into an error where `Propel::getDefaultDB` is returning `default` (the Propel default) instead of `conn1` which is defined as the default in the configuration.

`Propel::$defaultDBName` is defined as a string:

``` php
/**
 * @var string The db name that is specified as the default in the property file
 */
private static $defaultDBName;
```

In `PropelExtension::dbalLoad` there's code that's supposed to be aliasing the default connection:

``` php
// Alias the default connection if not defined
if (!isset($c['datasources']['default'])) {
    $c['datasources']['default'] = $c['datasources'][$connectionName];
}
```

The problem is that `$c['datasources'][$connectionName]` is an _array_, not a string containing the default connection name.

`Propel::getDefaultDB` is then calling `is_scalar` on an array which returns false:

``` php
self::$defaultDBName = isset(self::$configuration['datasources']['default']) // true
    && is_scalar(self::$configuration['datasources']['default']) // false
    ? self::$configuration['datasources']['default'] // can't reach here
    : self::DEFAULT_NAME; // returns "default"
```

Fix should be as simple as:

``` php
if (!isset($c['datasources']['default'])) {
    $c['datasources']['default'] = $connectionName; // use the default connection name - not the actual configuration
}
```
