### ISSUE TITLE
default datasource is a scaler, causes errors in generating model

### ISSUE THREAD

**Issue by tacman** [propelorm/PropelBundle#318]
It appears that the default datasource is coming out as a string instead of an array when getting the database connections:

        $propelConfiguration = $container->get('propel.configuration');
        foreach ($propelConfiguration['datasources'] as $name => $datasource) {

![image](https://cloud.githubusercontent.com/assets/619585/5691839/5ff9c050-98a8-11e4-98ec-6b3cab18f429.png)

This is causing it to fail when building models, since it assumes that the datasource array elements are all arrays:

            , array(
                '%name%'     => $name,
                '%adapter%'  => $datasource['adapter'],
                '%dsn%'      => $datasource['connection']['dsn'],
                '%username%' => $datasource['connection']['user'],
                '%password%' => isset($datasource['connection']['password']) ? $datasource['connection']['password'] : '',

Has there been a change in the way the default connection is configured?  It expects a scaler, if we leave it blank it defaults to 'default', if we explicitly set it to a connection name it still causes an error.

For the moment, we're trying to revert to an earlier commit: 0aee6aa0c952fde9eadc512936a3f5af07a56306

but composer is complaining that it can't find it.

Here's what I have in config.yml

```yaml
    dbal:
        classname: Glorpen\Propel\PropelBundle\Connection\EventPropelPDO
        default_connection:       posse
        connections:
           posse:
               driver:             %propel_driver%
               user:               %database_user%
               password:           %database_password%
               dsn:                %propel_driver%:host=%database_host%;dbname=%database_name%
           phenx:
               driver:             %propel_driver%
               user:               %database_user%
               password:           %database_password%
               dsn:                %propel_driver%:host=%database_host%;dbname=%database_name%
           ct:
               driver:             %propel_driver%
```` 

The error we're getting on building the model is:
![image](https://cloud.githubusercontent.com/assets/619585/5691861/452d7c20-98a9-11e4-951d-cd9913cb697d.png)
