### ISSUE TITLE
Install Propel 2 on Symfony 2.6

### ISSUE THREAD

**Issue by loicdev** [propelorm/PropelBundle#329]
Hi,

Recently i have realized that i have installed Propel 1.7.1 ant not Propel2 on Symfony 2 framework.
So i have decided to install it but i have some troubles to run it correctly.

i obtain this error : " No connection information in your runtime configuration file for datasource [default] "

My config:

```yaml
propel:
    database:
        connections:
            default:
                classname: Propel\Runtime\Connection\DebugPDO
                adapter:    %database_driver%
                user:       %database_user%
                password:   %database_password%
                dsn:  %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
    runtime:
        defaultConnection: default
        connections: [default]
    generator:
        defaultConnection: default
        connections: [default]
```
