### ISSUE TITLE
Debug Panel not working - Key "defaultConnection" missing

### ISSUE THREAD

**Issue by Xosofox** [propelorm/PropelBundle#365]
When I use the Propel Debug Panel in my project, it breaks with

Key "defaultConnection" for array with keys "connections, logging, log" does not exist in PropelBundle:Panel:configuration.html.twig at line 13

Looks like there is no "defaultConnection" that the {{ configuration.runtime.defaultConnection }} can spit out.

If I change the source and comment out that part, it works perfectly fine.

I would really like to fix this and provide a PR, but I am not sure what I am missing - if this is an inconsistency in my config (however, everything else works fine) or an assumption by the view that might not be met in every project?

Any hint on WHY it expects a "defaultConnection" key might help me to provide a PR

**Comment by marcj** [comment]
Do you mix maybe version 1 and 2? We have in PropelBundle for each version separat branches.

**Comment by Xosofox** [comment]
"php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        ...
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        ...
        "symfony/console": "2.7.x-dev",
        "symfony/filesystem": "2.7.x-dev",
        "symfony/finder": "2.7.x-dev",
        "propel/propel": "2.0.*@dev",
        "propel/propel-bundle": "~2.0@dev",

**Comment by Xosofox** [comment]
And honeslty, I've been reading the "Branching Model" explanation a hundred times since i was first released by will - and I still get confused...

Maye you can explain it once and for all to me and I'll try to rephrase it so my simple mind (and maybe some others out there) can understand it more easily

**Comment by marcj** [comment]
```
    "propel/propel": "2.0.*@dev",
    "propel/propel-bundle": "~2.0@dev",
```
That seems ok. We are using it this way in our projects as well and symfony profile stuff works perfectly well with Propel. Can you please show us `composer show --installed`?

**Comment by Xosofox** [comment]
I think I did everything quite straight forward from the books...

Installed:


    ...
    jdorn/sql-formatter                  v1.2.17            
    ...
    propel/propel                        dev-master 27bb4ec 
    propel/propel-bundle                 2.0.x-dev ec464b1  
    ...
    sensio/distribution-bundle           v4.0.3             
    sensio/framework-extra-bundle        v3.0.10            
    sensio/generator-bundle              v2.5.3             
    sensiolabs/security-checker          v3.0.1             
    swiftmailer/swiftmailer              v5.4.1             
    symfony/assetic-bundle               v2.7.0             
    symfony/console                      2.7.x-dev 7fc7b39  
    symfony/filesystem                   2.7.x-dev 419d91f  
    symfony/finder                       2.7.x-dev a06a0c0  
    symfony/monolog-bundle               2.8.1              
    symfony/swiftmailer-bundle           v2.3.8             
    symfony/symfony                      v2.7.6             
    twig/extensions                      v1.3.0             
    twig/twig                            v1.23.0            


config.yml
```yaml
#Propel config
# define the parameters in app/config/parameters.yml
propel:
    database:
        connections:
            default:
                adapter:    %database_driver%
                user:       %database_user%
                password:   %database_password%
                dsn:        %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
                settings:
                  charset: utf8
```

**Comment by Xosofox** [comment]
Here's a twig {{  dump(configuration.runtime) }} 

array:3 [▼
  "connections" => []
  "logging" => true
  "log" => []
]

Not too much...

**Comment by marcj** [comment]
```yaml
#Propel config
# define the parameters in app/config/parameters.yml
propel:
    database:
        connections:
            default:
                adapter:    %database_driver%
                user:       %database_user%
                password:   %database_password%
                dsn:        %database_driver%:host=%database_host%;dbname=%database_name%;charset=UTF8
                settings:
                  charset: utf8
    runtime:
        defaultConnection: default
    generator:
        defaultConnection: default
```

Could you try this please?
