### ISSUE TITLE
Profiler broken in PropelBundle 1.5.1

### ISSUE THREAD

**Issue by ghost** [propelorm/PropelBundle#430]
Hey,

I've this in my config:

```
# Propel Configuration
propel:
    dbal:
        default_connection: foo
        connections:
            foo:
                driver: mysql
                user: %database_user%
                password: %database_password%
                dsn: mysql:host=%database_host%;dbname=%database_name%;charset=UTF8
                options: {}
                attributes: {}
```

If I try to open the profiler, there is an error:

```
Impossible to access an attribute ("adapter") on a string variable ("foo") in PropelBundle:Panel:configuration.html.twig at line 45
```

When I specify the adapter instead of the driver there is another error:

```
Unrecognized option "adapter" under "propel.dbal.connections.foo"
```

What could be the reason for this?

```
propel/propel-bundle 1.5.1 Integration of Propel in Symfony2
propel/propel1 1.7.1 Propel is an open-source Object-Relational Mapping (ORM) for PHP5.
symfony/symfony v2.8.8 The Symfony PHP framework
```

Can anyone help?

Best,
Christian

**Comment by marcj** [comment]
I don't think old Propel is compatible with new Symfony 2.8.8.

**Comment by ghost** [comment]
Which version should I choose? I just did a composer require propel/propel-bundle. The Version was choosed automatically.

**Comment by ghost** [comment]
I switched back to PropelBundle 1.4.5. Error is gone now and profiler is working again. Anyway, I'll leave this open.

**Comment by marcj** [comment]
When possible upgrade to v2.

**Comment by ghost** [comment]
Unfortunately, not possible. :/ v2 is not compatible with FOSUserBundle.

**Comment by nibsirahsieu** [comment]
PR #429 should fix this issue.

For a while, you should rename your `foo` connection by `default`.

```
propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver: mysql
                user: %database_user%
                password: %database_password%
                dsn: mysql:host=%database_host%;dbname=%database_name%;charset=UTF8
                options: {}
                attributes: {}
```
