### ISSUE TITLE
Symfony 3.4  + Unique Fields validation not working

### ISSUE THREAD

**Issue by parthiv2585** [propelorm/PropelBundle#478]
Hi All ,
I have upgrade Symfony 2.8 to Symfony 3.4. Unique validation is working in Symfony 2.8 but in Symfony 3.4 get error as blow.

**My validation.yml file as below** 

```
Security\PersonBundle\Model\Person:
  constraints:
    - Propel\PropelBundle\Validator\Constraints\UniqueObject:
        fields: email
        message: Email already exists.
```

**ERROR** 
 
![screenshot-2017-12-8 attempted to load class uniqueobject from namespace symfony component validator constraints propel pro 1](https://user-images.githubusercontent.com/3072019/33755856-c27faa4e-dc18-11e7-8938-0473647008c1.png)

Please help to fixed this issue.
Thanks

**Comment by parthiv2585** [comment]
Hi All ,

I have fixed this issue. Please check updated code.

```
Security\PersonBundle\Model\Person:
  constraints:
    - Propel\Bundle\PropelBundle\Validator\Constraints\UniqueObject:
        fields: email
        message: Email already exists.
```
